<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" />
    <PackageReference Include="System.IO.Hashing" />
    <PackageReference Include="ZstdSharp.Port" />
  </ItemGroup>
  <ItemGroup Condition="Exists('$(VcpkgInstalledDir)\x64-windows\bin\zlib1.dll')">
    <Content Include="$(VcpkgInstalledDir)\x64-windows\bin\zlib1.dll"
             Link="zlib1.dll"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
