<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWinUI>true</UseWinUI>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableMsixTooling>true</EnableMsixTooling>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <SelfContained>true</SelfContained>
    <PublishTrimmed>false</PublishTrimmed>
    <PublishSingleFile>false</PublishSingleFile>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace>XDecode.WindowsApp</RootNamespace>
    <NoWarn>$(NoWarn);SYSLIB1054</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\XDecode.Application\XDecode.Application.csproj" />
    <ProjectReference Include="..\XDecode.Core\XDecode.Core.csproj" />
    <PackageReference Include="Microsoft.WindowsAppSDK" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" />
  </ItemGroup>
</Project>
